# Generated by Django 5.1.3 on 2025-01-28 10:26

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tender", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="VacanciApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fullname",
                    models.CharField(max_length=255, verbose_name="Название компании"),
                ),
                (
                    "phone",
                    models.CharField(max_length=123, verbose_name="Номер телефона"),
                ),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="Электронная почта"),
                ),
                ("comment", models.TextField(verbose_name="Комментарий")),
                (
                    "csv",
                    models.FileField(
                        upload_to="application_files/", verbose_name="Резюме"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
            ],
            options={
                "verbose_name": "Заявка вакансии",
                "verbose_name_plural": "Заявки вакансии",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Vacancies",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "usloviya",
                    ckeditor.fields.RichTextField(verbose_name="Условия работы"),
                ),
                (
                    "phone",
                    models.CharField(max_length=123, verbose_name="Номер телефона"),
                ),
            ],
            options={
                "verbose_name": "Вакансии",
                "verbose_name_plural": "Вакансии",
            },
        ),
    ]
