# Generated by Django 5.1.3 on 2025-02-03 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tender", "0003_tender_file_tender_organization_tender_place_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contacts",
            name="tender",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contacts_tender",
                to="tender.tender",
            ),
        ),
        migrations.AlterField(
            model_name="requirement",
            name="tender",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="requers",
                to="tender.tender",
            ),
        ),
    ]
