# Generated by Django 5.1.3 on 2025-03-31 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tender", "0004_alter_contacts_tender_alter_requirement_tender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vacanciapplication",
            name="csv",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="application_files/",
                verbose_name="Резюме",
            ),
        ),
    ]
