version: "3.10"

services:
  postgres:
    image: postgres:latest
    restart: always
    env_file:
      - .env

    volumes:
      - "./postgres:/var/lib/postgresql/data"

  app:
    build: .
    volumes:
      - .:/core
      - ./apps/static:/app/apps/static
      - ./apps/media:/app/apps/media
    ports:
      - "8000:8000"
    command: bash -c "python manage.py collectstatic --no-input && python manage.py showmigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"

    env_file:
      - .env
    depends_on:
      - postgres
    restart: always
