# Generated by Django 5.1.3 on 2024-12-13 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LinkNews",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Заголовок")),
                ("url", models.URLField(verbose_name="URL")),
                (
                    "image",
                    models.ImageField(
                        upload_to="images/link_news/", verbose_name="Изображение"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
            ],
            options={
                "verbose_name": "Ссылка на новость",
                "verbose_name_plural": "Ссылки на новости",
                "ordering": ["-created_at"],
            },
        ),
    ]
