# Generated by Django 5.1.3 on 2025-01-07 16:13

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.FileField(upload_to='files/')),
                ('first_key', models.CharField(max_length=123)),
                ('second_key', models.CharField(max_length=123)),
                ('third_key', models.CharField(max_length=123)),
                ('first_value', models.CharField(max_length=123)),
                ('second_value', models.CharField(max_length=123)),
                ('third_value', models.CharField(max_length=123)),
                ('address', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name': 'Домашняя страница',
                'verbose_name_plural': 'Домашняя страница',
            },
        ),
    ]
