# Generated by Django 5.1.3 on 2025-01-13 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_remove_homeinfo_address_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homeinfo",
            name="first_value",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="homeinfo",
            name="second_value",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="homeinfo",
            name="third_value",
            field=models.IntegerField(default=0),
        ),
    ]
