# Generated by Django 5.1.3 on 2025-01-22 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_homeinfo_first_value_and_more'),
        ('info', '0003_remove_contacts_addresses_remove_contacts_requisites_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='contacts',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addresss', to='info.contacts'),
        ),
    ]
