# Generated by Django 5.1.3 on 2025-07-08 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_address_contacts"),
    ]

    operations = [
        migrations.CreateModel(
            name="AddressFooter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("link", models.URLField()),
                ("title", models.CharField(max_length=255)),
            ],
        ),
    ]
