# Generated by Django 5.1.3 on 2024-12-01 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Advantage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=123)),
                ("svg", models.FileField(upload_to="svg/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Building",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=123, verbose_name="Название")),
                ("mini_title", models.CharField(max_length=123)),
                ("banner", models.ImageField(upload_to="images/banners/")),
                ("buklet", models.FileField(upload_to="files/buklets/")),
                ("first_image", models.ImageField(upload_to="images/buildings/")),
                ("description", models.TextField()),
                ("address", models.CharField(max_length=123)),
                ("max_blocks", models.IntegerField()),
                ("max_apartment", models.IntegerField()),
                ("plot_area", models.FloatField()),
                ("parking_spaces", models.IntegerField()),
                ("low_rise_blocks", models.IntegerField()),
                ("construction_area", models.IntegerField()),
                ("appartament_quantity", models.IntegerField()),
                ("yard_area", models.FloatField()),
                ("green_area", models.FloatField()),
                ("childrens_playgrounds", models.IntegerField()),
                ("day_image", models.ImageField(upload_to="images/buildings/")),
                ("night_image", models.ImageField(upload_to="images/buildings/")),
                (
                    "under_parking_layout",
                    models.ImageField(upload_to="images/buildings/"),
                ),
                (
                    "location_image_first",
                    models.ImageField(upload_to="images/buildings/"),
                ),
                (
                    "location_image_second",
                    models.ImageField(upload_to="images/buildings/"),
                ),
                ("youtube_url", models.URLField()),
                ("live_url", models.URLField()),
                ("etaps_url", models.URLField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Categry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=123)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="InterestingNearby",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=123)),
                ("image", models.ImageField(upload_to="images/other/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="InterestingNearbyBuilding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time", models.CharField(max_length=123)),
                (
                    "building",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="interetes",
                        to="objects.building",
                    ),
                ),
                (
                    "interesting_nearby",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="objects.interestingnearby",
                    ),
                ),
            ],
        ),
    ]
