# Generated by Django 5.1.3 on 2024-12-07 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Advantage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=123)),
                ("svg", models.FileField(upload_to="svg/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=123)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="FloorSchema",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=123)),
            ],
        ),
        migrations.CreateModel(
            name="ImageGallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="images/gallery/")),
            ],
        ),
        migrations.CreateModel(
            name="InterestingNearby",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=123)),
                ("image", models.ImageField(upload_to="images/other/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Building",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        max_length=255,
                        null=True,
                        unique=True,
                        verbose_name="Слаг",
                    ),
                ),
                ("title", models.CharField(max_length=123, verbose_name="Название")),
                ("mini_title", models.CharField(max_length=123)),
                ("banner", models.ImageField(upload_to="images/banners/")),
                ("buklet", models.FileField(upload_to="files/buklets/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="objects.category",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BlockInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=211)),
                ("image", models.ImageField(upload_to="images/buildings/")),
                (
                    "floor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocks",
                        to="objects.floorschema",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InterestingNearbyBuilding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time", models.CharField(max_length=123)),
                (
                    "building",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="interetes",
                        to="objects.building",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Section1",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_image", models.ImageField(upload_to="images/buildings/")),
                ("description", models.TextField()),
                ("address", models.CharField(max_length=123)),
                ("max_blocks", models.IntegerField()),
                (
                    "building",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="section_1",
                        to="objects.building",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Section2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("max_apartment", models.IntegerField()),
                ("plot_area", models.FloatField()),
                ("parking_spaces", models.IntegerField()),
                ("low_rise_blocks", models.IntegerField()),
                ("construction_area", models.IntegerField()),
                ("appartament_quantity", models.IntegerField()),
                ("yard_area", models.FloatField()),
                ("green_area", models.FloatField()),
                ("childrens_playgrounds", models.IntegerField()),
                (
                    "building",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="section_2",
                        to="objects.building",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Section3",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day_image", models.ImageField(upload_to="images/buildings/")),
                ("night_image", models.ImageField(upload_to="images/buildings/")),
                (
                    "building",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="section_3",
                        to="objects.building",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Section4",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "under_parking_layout",
                    models.ImageField(upload_to="images/buildings/"),
                ),
                (
                    "building",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="section_4",
                        to="objects.building",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Section5",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "building",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="section_5",
                        to="objects.building",
                    ),
                ),
                ("images", models.ManyToManyField(to="objects.imagegallery")),
            ],
        ),
        migrations.CreateModel(
            name="Section6",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("advantages", models.ManyToManyField(to="objects.advantage")),
                (
                    "building",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="section_6",
                        to="objects.building",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Section7",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "building",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="section_7",
                        to="objects.building",
                    ),
                ),
                (
                    "interest_nearby",
                    models.ManyToManyField(to="objects.interestingnearbybuilding"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Section8",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location_description", models.TextField()),
                (
                    "location_image_first",
                    models.ImageField(upload_to="images/buildings/"),
                ),
                (
                    "location_image_second",
                    models.ImageField(upload_to="images/buildings/"),
                ),
                (
                    "building",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="section_8",
                        to="objects.building",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Section9",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("youtube_url", models.URLField()),
                ("live_url", models.URLField()),
                ("etaps_url", models.URLField()),
                (
                    "building",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="section_9",
                        to="objects.building",
                    ),
                ),
            ],
        ),
    ]
