# Generated by Django 5.1.3 on 2024-12-07 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("objects", "0002_architecture_features_alter_section1_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="building",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Объект",
                "verbose_name_plural": "Объекты",
            },
        ),
        migrations.AlterModelOptions(
            name="section1",
            options={
                "verbose_name": "О комплексе",
                "verbose_name_plural": "О комплексе",
            },
        ),
        migrations.AlterModelOptions(
            name="section10",
            options={"verbose_name": "Локация", "verbose_name_plural": "Локация"},
        ),
        migrations.AlterModelOptions(
            name="section11",
            options={"verbose_name": "Футер", "verbose_name_plural": "Футер"},
        ),
        migrations.AlterModelOptions(
            name="section2",
            options={"verbose_name": "В цифрах", "verbose_name_plural": "В цифрах"},
        ),
        migrations.AlterModelOptions(
            name="section3",
            options={
                "verbose_name": "День и Ночь",
                "verbose_name_plural": "День и Ночь",
            },
        ),
        migrations.AlterModelOptions(
            name="section4",
            options={
                "verbose_name": "Планы этажей",
                "verbose_name_plural": "Планы этажей",
            },
        ),
        migrations.AlterModelOptions(
            name="section5",
            options={
                "verbose_name": "Подземная парковка",
                "verbose_name_plural": "Подземная парковка",
            },
        ),
        migrations.AlterModelOptions(
            name="section6",
            options={
                "verbose_name": "Архитектура",
                "verbose_name_plural": "Архитектура",
            },
        ),
        migrations.AlterModelOptions(
            name="section7",
            options={"verbose_name": "Галерея", "verbose_name_plural": "Галерея"},
        ),
        migrations.AlterModelOptions(
            name="section8",
            options={
                "verbose_name": "Преимущества",
                "verbose_name_plural": "Преимущества",
            },
        ),
        migrations.AlterModelOptions(
            name="section9",
            options={
                "verbose_name": "Интересное рядом",
                "verbose_name_plural": "Интересное рядом",
            },
        ),
        migrations.RemoveField(
            model_name="blockinfo",
            name="floor",
        ),
        migrations.AddField(
            model_name="floorschema",
            name="blocks",
            field=models.ManyToManyField(to="objects.blockinfo"),
        ),
    ]
