# Generated by Django 5.1.3 on 2024-12-07 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("objects", "0003_alter_building_options_alter_section1_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="advantage",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Преимущество",
                "verbose_name_plural": "Преимущества",
            },
        ),
        migrations.AlterModelOptions(
            name="architecture",
            options={
                "verbose_name": "Архитектура",
                "verbose_name_plural": "Архитектура",
            },
        ),
        migrations.AlterModelOptions(
            name="blockinfo",
            options={"verbose_name": "Блок", "verbose_name_plural": "Блоки"},
        ),
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
            },
        ),
        migrations.AlterModelOptions(
            name="features",
            options={"verbose_name": "Функция", "verbose_name_plural": "Функции"},
        ),
        migrations.AlterModelOptions(
            name="floorschema",
            options={
                "verbose_name": "Планировка этажа",
                "verbose_name_plural": "Планировки этажей",
            },
        ),
        migrations.AlterModelOptions(
            name="interestingnearby",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Интересное место",
                "verbose_name_plural": "Интересные места",
            },
        ),
        migrations.AlterModelOptions(
            name="interestingnearbybuilding",
            options={
                "verbose_name": "Интересное место для объекта",
                "verbose_name_plural": "Интересные места для объектов",
            },
        ),
        migrations.AlterField(
            model_name="building",
            name="banner",
            field=models.FileField(upload_to="images/banners/"),
        ),
        migrations.AlterField(
            model_name="interestingnearbybuilding",
            name="building",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="interetes",
                to="objects.interestingnearby",
            ),
        ),
    ]
