# Generated by Django 5.1.3 on 2024-12-07 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("objects", "0004_alter_advantage_options_alter_architecture_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="section7",
            name="building",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="section_7",
                to="objects.building",
            ),
        ),
    ]
