# Generated by Django 5.1.3 on 2024-12-10 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("objects", "0005_alter_section7_building"),
    ]

    operations = [
        migrations.AddField(
            model_name="building",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "В процессе"),
                    ("archive", "Архив"),
                    ("ended", "Реализовано"),
                ],
                default=1,
                max_length=123,
            ),
            preserve_default=False,
        ),
    ]
