# Generated by Django 5.1.3 on 2024-12-13 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("objects", "0006_building_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConstructionProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "month",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "01"),
                            (2, "02"),
                            (3, "03"),
                            (4, "04"),
                            (5, "05"),
                            (6, "06"),
                            (7, "07"),
                            (8, "08"),
                            (9, "09"),
                            (10, "10"),
                            (11, "11"),
                            (12, "12"),
                        ],
                        verbose_name="Месяц",
                    ),
                ),
                ("year", models.PositiveIntegerField(verbose_name="Год")),
                (
                    "building",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="construction_progress",
                        to="objects.building",
                        verbose_name="Здание",
                    ),
                ),
            ],
            options={
                "verbose_name": "Динамика строительства",
                "verbose_name_plural": "Динамика строительства",
                "ordering": ["-year", "-month"],
            },
        ),
        migrations.CreateModel(
            name="ConstructionProgressImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="images/construction_progress/",
                        verbose_name="Изображение",
                    ),
                ),
                (
                    "construction_progress",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="objects.constructionprogress",
                        verbose_name="Динамика строительства",
                    ),
                ),
            ],
            options={
                "verbose_name": "Изображение динамики строительства",
                "verbose_name_plural": "Изображения динамики строительства",
            },
        ),
    ]
