# Generated by Django 5.1.3 on 2025-01-13 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("objects", "0010_remove_section7_images_imagegallery_section7_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="building",
            name="imagebg",
            field=models.ImageField(default=1, upload_to="images/bgs/"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="building",
            name="imagepng",
            field=models.ImageField(blank=True, null=True, upload_to="images/bgs/"),
        ),
    ]
