# Generated by Django 5.1.3 on 2025-01-14 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("objects", "0011_building_imagebg_building_imagepng"),
    ]

    operations = [
        migrations.AddField(
            model_name="building",
            name="is_new",
            field=models.BooleanField(default=False),
        ),
    ]
