# Generated by Django 5.1.3 on 2025-01-19 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0013_building_banner_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advantage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создание'),
        ),
        migrations.AlterField(
            model_name='advantage',
            name='svg',
            field=models.FileField(upload_to='svg/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='advantage',
            name='title',
            field=models.CharField(max_length=123, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='architecture',
            name='features',
            field=models.ManyToManyField(to='objects.features', verbose_name='Фича'),
        ),
        migrations.AlterField(
            model_name='architecture',
            name='title',
            field=models.CharField(max_length=123, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='blockinfo',
            name='image',
            field=models.ImageField(upload_to='images/buildings/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='blockinfo',
            name='title',
            field=models.CharField(max_length=211, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='building',
            name='banner',
            field=models.FileField(upload_to='images/banners/', verbose_name='Видео'),
        ),
        migrations.AlterField(
            model_name='building',
            name='banner_img',
            field=models.FileField(blank=True, null=True, upload_to='images/banners/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='building',
            name='buklet',
            field=models.FileField(upload_to='files/buklets/', verbose_name='Буклет'),
        ),
        migrations.AlterField(
            model_name='building',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='objects.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='building',
            name='imagebg',
            field=models.ImageField(upload_to='images/bgs/', verbose_name='Фоновое изображение'),
        ),
        migrations.AlterField(
            model_name='building',
            name='imagepng',
            field=models.ImageField(blank=True, null=True, upload_to='images/bgs/', verbose_name='Изображение PNG'),
        ),
        migrations.AlterField(
            model_name='building',
            name='is_new',
            field=models.BooleanField(default=False, verbose_name='Новинка'),
        ),
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создание'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=123, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='features',
            name='mini_description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='features',
            name='title',
            field=models.CharField(max_length=123, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='floorschema',
            name='blocks',
            field=models.ManyToManyField(to='objects.blockinfo', verbose_name='Блоки'),
        ),
        migrations.AlterField(
            model_name='floorschema',
            name='title',
            field=models.CharField(max_length=123, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='imagegallery',
            name='image',
            field=models.ImageField(upload_to='images/gallery/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='imagegallery',
            name='section7',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='section_images', to='objects.section7', verbose_name='Объект'),
        ),
        migrations.AlterField(
            model_name='interestingnearby',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создание'),
        ),
        migrations.AlterField(
            model_name='interestingnearby',
            name='image',
            field=models.ImageField(upload_to='images/other/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='interestingnearby',
            name='title',
            field=models.CharField(max_length=123, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='interestingnearbybuilding',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='interetes', to='objects.interestingnearby', verbose_name='Объект'),
        ),
        migrations.AlterField(
            model_name='interestingnearbybuilding',
            name='time',
            field=models.CharField(max_length=123, verbose_name='Время от обьекта'),
        ),
        migrations.AlterField(
            model_name='section1',
            name='address',
            field=models.CharField(max_length=123, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='section1',
            name='building',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='section_1', to='objects.building', verbose_name='Объект'),
        ),
        migrations.AlterField(
            model_name='section1',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='section1',
            name='first_image',
            field=models.ImageField(upload_to='images/buildings/', verbose_name='Первое изображение'),
        ),
        migrations.AlterField(
            model_name='section1',
            name='max_apartment',
            field=models.IntegerField(verbose_name='Аппартаменты'),
        ),
        migrations.AlterField(
            model_name='section1',
            name='max_blocks',
            field=models.IntegerField(verbose_name='Блоки'),
        ),
        migrations.AlterField(
            model_name='section1',
            name='second_image',
            field=models.ImageField(upload_to='images/buildings/', verbose_name='Второе изображение'),
        ),
        migrations.AlterField(
            model_name='section10',
            name='building',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='section_10', to='objects.building', verbose_name='Объект'),
        ),
        migrations.AlterField(
            model_name='section10',
            name='location_description',
            field=models.TextField(verbose_name='Описание локации'),
        ),
        migrations.AlterField(
            model_name='section10',
            name='location_iframe_url',
            field=models.TextField(verbose_name='Ссылка адреса'),
        ),
        migrations.AlterField(
            model_name='section10',
            name='location_image_first',
            field=models.ImageField(upload_to='images/buildings/', verbose_name='Первое изображение'),
        ),
        migrations.AlterField(
            model_name='section10',
            name='location_image_second',
            field=models.ImageField(upload_to='images/buildings/', verbose_name='Второе изображение'),
        ),
        migrations.AlterField(
            model_name='section11',
            name='building',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='section_11', to='objects.building', verbose_name='Объект'),
        ),
        migrations.AlterField(
            model_name='section11',
            name='live_url',
            field=models.URLField(verbose_name=''),
        ),
        migrations.AlterField(
            model_name='section11',
            name='youtube_url',
            field=models.URLField(verbose_name=''),
        ),
        migrations.AlterField(
            model_name='section2',
            name='appartament_quantity',
            field=models.IntegerField(verbose_name='Количество квартир'),
        ),
        migrations.AlterField(
            model_name='section2',
            name='building',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='section_2', to='objects.building', verbose_name='Объект'),
        ),
        migrations.AlterField(
            model_name='section2',
            name='childrens_playgrounds',
            field=models.IntegerField(verbose_name='Детских площадок'),
        ),
        migrations.AlterField(
            model_name='section2',
            name='construction_area',
            field=models.IntegerField(verbose_name='Площадь застройки'),
        ),
        migrations.AlterField(
            model_name='section2',
            name='first_image',
            field=models.ImageField(upload_to='images', verbose_name='Первое изображение'),
        ),
        migrations.AlterField(
            model_name='section2',
            name='green_area',
            field=models.FloatField(verbose_name='Площадь озеленения'),
        ),
        migrations.AlterField(
            model_name='section2',
            name='low_rise_blocks',
            field=models.IntegerField(verbose_name='Малоэтажных блоков'),
        ),
        migrations.AlterField(
            model_name='section2',
            name='parking_spaces',
            field=models.IntegerField(verbose_name='Парковочных мест'),
        ),
        migrations.AlterField(
            model_name='section2',
            name='plot_area',
            field=models.FloatField(verbose_name='Площадь участка'),
        ),
        migrations.AlterField(
            model_name='section2',
            name='second_image',
            field=models.ImageField(upload_to='images', verbose_name='Второе изображение'),
        ),
        migrations.AlterField(
            model_name='section2',
            name='yard_area',
            field=models.FloatField(verbose_name='Площадь двора'),
        ),
        migrations.AlterField(
            model_name='section3',
            name='building',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='section_3', to='objects.building', verbose_name='Объект'),
        ),
        migrations.AlterField(
            model_name='section3',
            name='day_image',
            field=models.ImageField(upload_to='images/buildings/', verbose_name='Дневное изображение'),
        ),
        migrations.AlterField(
            model_name='section3',
            name='night_image',
            field=models.ImageField(upload_to='images/buildings/', verbose_name='Ночное изображение'),
        ),
        migrations.AlterField(
            model_name='section4',
            name='building',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='section_4', to='objects.building', verbose_name='Объект'),
        ),
        migrations.AlterField(
            model_name='section4',
            name='floorschemas',
            field=models.ManyToManyField(to='objects.floorschema', verbose_name='Схема этажей'),
        ),
        migrations.AlterField(
            model_name='section5',
            name='building',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='section_5', to='objects.building', verbose_name='Объект'),
        ),
        migrations.AlterField(
            model_name='section5',
            name='under_parking_layout',
            field=models.ImageField(upload_to='images/buildings/', verbose_name='Подземная парковка'),
        ),
        migrations.AlterField(
            model_name='section6',
            name='architecture',
            field=models.ManyToManyField(to='objects.architecture', verbose_name='Архитектура'),
        ),
        migrations.AlterField(
            model_name='section6',
            name='building',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='section_6', to='objects.building', verbose_name='Объект'),
        ),
        migrations.AlterField(
            model_name='section7',
            name='building',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='section_7', to='objects.building', verbose_name='Объект'),
        ),
        migrations.AlterField(
            model_name='section8',
            name='advantages',
            field=models.ManyToManyField(to='objects.advantage', verbose_name='Преимущества'),
        ),
        migrations.AlterField(
            model_name='section8',
            name='building',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='section_8', to='objects.building', verbose_name='Объект'),
        ),
        migrations.AlterField(
            model_name='section9',
            name='building',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='section_9', to='objects.building', verbose_name='Объект'),
        ),
        migrations.AlterField(
            model_name='section9',
            name='interest_nearby',
            field=models.ManyToManyField(to='objects.interestingnearbybuilding', verbose_name='Интересные места'),
        ),
    ]
