# Generated by Django 5.1.3 on 2025-01-19 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0014_alter_advantage_created_at_alter_advantage_svg_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='floorschema',
            name='blocks',
        ),
        migrations.RemoveField(
            model_name='section4',
            name='floorschemas',
        ),
        migrations.AddField(
            model_name='blockinfo',
            name='floorschema',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='floorschema_blocks', to='objects.floorschema', verbose_name='Блоки'),
        ),
        migrations.AddField(
            model_name='floorschema',
            name='section4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='section_floors', to='objects.section4', verbose_name='Объект'),
        ),
    ]
