# Generated by Django 5.1.3 on 2025-01-19 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0015_remove_floorschema_blocks_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='architecture',
            name='features',
        ),
        migrations.AddField(
            model_name='features',
            name='Architecture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Architecture_blocks', to='objects.architecture', verbose_name='Архитектура'),
        ),
    ]
