# Generated by Django 5.1.3 on 2025-01-19 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0016_remove_architecture_features_features_architecture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section6',
            name='architecture',
        ),
        migrations.AddField(
            model_name='architecture',
            name='section6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Architecture_blocks', to='objects.section6', verbose_name='Архитектура'),
        ),
    ]
