# Generated by Django 5.1.3 on 2025-01-19 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0018_remove_section9_interest_nearby_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='section6',
            options={'verbose_name': 'Секция архитектуры в обьекте', 'verbose_name_plural': 'Секция архитектуры в обьекте'},
        ),
        migrations.AlterModelOptions(
            name='section9',
            options={'verbose_name': 'Интересное рядом с Объектом', 'verbose_name_plural': 'Интересное рядом с Объектом'},
        ),
    ]
