# Generated by Django 5.1.3 on 2025-01-19 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0021_alter_blockinfo_options_alter_floorschema_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockinfo',
            name='image',
            field=models.FileField(upload_to='images/buildings/', verbose_name='Изображение'),
        ),
    ]
