# Generated by Django 5.1.3 on 2025-01-19 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0022_alter_blockinfo_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section5',
            name='under_parking_layout',
        ),
        migrations.CreateModel(
            name='ParkingImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('under_parking_layout', models.ImageField(upload_to='images/buildings/', verbose_name='Подземная парковка')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ParkingImages_blocks', to='objects.section5', verbose_name='Секция')),
            ],
            options={
                'verbose_name': 'Подземная парковка изображении',
                'verbose_name_plural': 'Подземная парковка изображении',
            },
        ),
        migrations.CreateModel(
            name='Section12',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='images/buildings/', verbose_name='Изображение')),
                ('gen_plan', models.FileField(upload_to='files/buildings/', verbose_name='Ген план')),
                ('building', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='section_12', to='objects.building', verbose_name='Объект')),
            ],
            options={
                'verbose_name': 'Нумерация',
                'verbose_name_plural': 'Нумерация',
            },
        ),
    ]
