# Generated by Django 5.1.3 on 2025-01-19 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0023_remove_section5_under_parking_layout_parkingimages_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingimages',
            name='title',
            field=models.CharField(default=1, max_length=255, verbose_name='Название'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Apartments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=123)),
                ('section1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Apartments_blocks', to='objects.section1', verbose_name='Секция')),
            ],
            options={
                'verbose_name': 'Квартиры',
                'verbose_name_plural': 'Квартиры',
            },
        ),
    ]
