# Generated by Django 5.1.3 on 2025-01-19 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0024_parkingimages_title_apartments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingimages',
            name='under_parking_layout',
            field=models.FileField(upload_to='images/buildings/', verbose_name='Подземная парковка'),
        ),
    ]
