# Generated by Django 5.1.3 on 2025-01-19 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0025_alter_parkingimages_under_parking_layout'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='priority',
            field=models.IntegerField(default=1, verbose_name='Приоритетность'),
            preserve_default=False,
        ),
    ]
