# Generated by Django 5.1.3 on 2025-01-21 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0026_building_priority'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='building',
            options={'ordering': ['priority'], 'verbose_name': 'Объект', 'verbose_name_plural': 'Объекты'},
        ),
        migrations.AddField(
            model_name='architecture',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='images/building/'),
        ),
    ]
