# Generated by Django 5.1.3 on 2025-01-30 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("objects", "0027_alter_building_options_architecture_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="building",
            name="bitrix",
            field=models.TextField(
                blank=True, null=True, verbose_name="Битрикс ссылка"
            ),
        ),
        migrations.AddField(
            model_name="building",
            name="threed",
            field=models.TextField(blank=True, null=True, verbose_name="3d"),
        ),
    ]
