# Generated by Django 5.1.3 on 2025-02-03 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("objects", "0028_building_bitrix_building_threed"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="building",
            name="threed",
        ),
        migrations.CreateModel(
            name="ThreeD",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=123, null=True, verbose_name="Название"
                    ),
                ),
                ("threed", models.TextField(blank=True, null=True, verbose_name="3d")),
                (
                    "building",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="threedes",
                        to="objects.building",
                    ),
                ),
            ],
        ),
    ]
