# Generated by Django 5.1.3 on 2025-02-03 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("objects", "0029_remove_building_threed_threed"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="threed",
            options={"verbose_name": "3д", "verbose_name_plural": "3д"},
        ),
        migrations.AddField(
            model_name="floorschema",
            name="image",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="images/buildings/",
                verbose_name="Изображение",
            ),
        ),
    ]
