# Generated by Django 5.1.3 on 2025-02-03 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("objects", "0030_alter_threed_options_floorschema_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="building",
            name="banner_phones",
            field=models.FileField(
                blank=True, null=True, upload_to="images/banners/", verbose_name="Видео"
            ),
        ),
    ]
