# Generated by Django 5.1.3 on 2025-02-05 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("objects", "0031_building_banner_phones"),
    ]

    operations = [
        migrations.AlterField(
            model_name="section10",
            name="location_image_first",
            field=models.FileField(
                upload_to="images/buildings/", verbose_name="Первое изображение"
            ),
        ),
        migrations.AlterField(
            model_name="section10",
            name="location_image_second",
            field=models.FileField(
                upload_to="images/buildings/", verbose_name="Второе изображение"
            ),
        ),
    ]
