# Generated by Django 5.1.3 on 2025-02-06 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("objects", "0033_alter_section11_live_url_alter_section11_youtube_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="building",
            name="banner_phones",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="images/banners/",
                verbose_name="Видео на телефон",
            ),
        ),
    ]
