# Generated by Django 5.1.3 on 2025-03-05 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0034_alter_building_banner_phones'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blockinfo',
            options={'ordering': ['-created_at'], 'verbose_name': 'Планы этажа', 'verbose_name_plural': 'Планы этажей'},
        ),
        migrations.AlterModelOptions(
            name='floorschema',
            options={'ordering': ['-created_at'], 'verbose_name': 'Планировка блока', 'verbose_name_plural': 'Планировки блоков'},
        ),
        migrations.AddField(
            model_name='blockinfo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='floorschema',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
