# Generated by Django 5.1.3 on 2025-03-12 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0036_alter_blockinfo_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='banner',
            field=models.FileField(blank=True, null=True, upload_to='images/banners/', verbose_name='Видео'),
        ),
        migrations.AlterField(
            model_name='building',
            name='buklet',
            field=models.FileField(blank=True, null=True, upload_to='files/buklets/', verbose_name='Буклет'),
        ),
        migrations.AlterField(
            model_name='building',
            name='imagebg',
            field=models.ImageField(blank=True, null=True, upload_to='images/bgs/', verbose_name='Фоновое изображение'),
        ),
        migrations.AlterField(
            model_name='building',
            name='is_new',
            field=models.BooleanField(blank=True, default=False, verbose_name='Новинка'),
        ),
        migrations.AlterField(
            model_name='building',
            name='mini_title',
            field=models.CharField(blank=True, max_length=123, null=True, verbose_name='Серия'),
        ),
        migrations.AlterField(
            model_name='building',
            name='priority',
            field=models.IntegerField(blank=True, null=True, verbose_name='Приоритетность'),
        ),
    ]
