# Generated by Django 5.1.3 on 2025-03-12 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0037_alter_building_banner_alter_building_buklet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section10',
            name='location_image_first',
            field=models.FileField(blank=True, null=True, upload_to='images/buildings/', verbose_name='Первое изображение'),
        ),
        migrations.AlterField(
            model_name='section10',
            name='location_image_second',
            field=models.FileField(blank=True, null=True, upload_to='images/buildings/', verbose_name='Второе изображение'),
        ),
    ]
