# Generated by Django 5.1.3 on 2025-03-17 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("objects", "0038_alter_section10_location_image_first_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="section1",
            name="address",
            field=models.CharField(
                blank=True, max_length=123, null=True, verbose_name="Адрес"
            ),
        ),
        migrations.AlterField(
            model_name="section1",
            name="building",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="section_1",
                to="objects.building",
                verbose_name="Объект",
            ),
        ),
        migrations.AlterField(
            model_name="section1",
            name="first_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="images/buildings/",
                verbose_name="Первое изображение",
            ),
        ),
        migrations.AlterField(
            model_name="section1",
            name="max_apartment",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Аппартаменты"
            ),
        ),
        migrations.AlterField(
            model_name="section1",
            name="max_blocks",
            field=models.IntegerField(blank=True, null=True, verbose_name="Блоки"),
        ),
        migrations.AlterField(
            model_name="section1",
            name="second_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="images/buildings/",
                verbose_name="Второе изображение",
            ),
        ),
    ]
