# Generated by Django 5.1.3 on 2025-03-18 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("objects", "0039_alter_section1_address_alter_section1_building_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="imagegallery",
            name="created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
