# Generated by Django 5.1.3 on 2025-03-19 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("objects", "0040_imagegallery_created_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="imagegallery",
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="Numeric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="название")),
                ("value", models.CharField(max_length=255, verbose_name="значение")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "section2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="section_numerics",
                        to="objects.section2",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
