# Generated by Django 5.1.3 on 2025-04-07 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("objects", "0041_alter_imagegallery_options_numeric"),
    ]

    operations = [
        migrations.AlterField(
            model_name="section1",
            name="max_apartment",
            field=models.CharField(blank=True, null=True, verbose_name="Аппартаменты"),
        ),
        migrations.AlterField(
            model_name="section1",
            name="max_blocks",
            field=models.CharField(blank=True, null=True, verbose_name="Блоки"),
        ),
    ]
