# Generated by Django 5.1.3 on 2025-04-07 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("objects", "0042_alter_section1_max_apartment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="building",
            name="mini_description",
            field=models.CharField(
                blank=True, max_length=80, null=True, verbose_name="Мини описание"
            ),
        ),
        migrations.AlterField(
            model_name="section1",
            name="max_blocks",
            field=models.CharField(
                blank=True, null=True, verbose_name="Блоки, Резиденции"
            ),
        ),
    ]
