# Generated by Django 5.1.3 on 2026-01-08 12:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("objects", "0043_building_mini_description_alter_section1_max_blocks"),
    ]

    operations = [
        migrations.AddField(
            model_name="building",
            name="logo",
            field=models.FileField(
                blank=True, null=True, upload_to="images/logos/", verbose_name="Логотип"
            ),
        ),
    ]
