# Generated by Django 5.1.3 on 2026-01-08 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("objects", "0044_building_domain_building_logo"),
    ]

    operations = [
        migrations.CreateModel(
            name="Requisites",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        default="ОсОО «Строительная компания «Авангард стиль»",
                        max_length=255,
                        verbose_name="Название компании",
                    ),
                ),
                (
                    "inn",
                    models.CharField(
                        default="00412199810063 999 УГКНС ККН",
                        max_length=123,
                        verbose_name="ИНН",
                    ),
                ),
                (
                    "okpo",
                    models.CharField(
                        default="22116708", max_length=123, verbose_name="ОКПО"
                    ),
                ),
                (
                    "building",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requisite",
                        to="objects.building",
                        verbose_name="Здание",
                    ),
                ),
            ],
            options={
                "verbose_name": "Реквизиты",
                "verbose_name_plural": "Реквизиты",
            },
        ),
        migrations.CreateModel(
            name="AddressBuilding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=233, verbose_name="Название")),
                ("value", models.CharField(max_length=233, verbose_name="Адрес")),
                ("link", models.URLField(verbose_name="Ссылка на адрес")),
                (
                    "building",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addresses",
                        to="objects.requisites",
                        verbose_name="Здание",
                    ),
                ),
            ],
            options={
                "verbose_name": "Адрес",
                "verbose_name_plural": "Адреса",
            },
        ),
        migrations.CreateModel(
            name="RequisitesInDollarBuilding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Название")),
                ("description", models.TextField(verbose_name="Описание")),
                (
                    "building",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dollar_requisites",
                        to="objects.requisites",
                        verbose_name="Здание",
                    ),
                ),
            ],
            options={
                "verbose_name": "Реквизиты в долларах",
                "verbose_name_plural": "Реквизиты в долларах",
            },
        ),
        migrations.CreateModel(
            name="RequisitesInSomBuilding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Название")),
                ("description", models.TextField(verbose_name="Описание")),
                (
                    "building",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="som_requisites",
                        to="objects.requisites",
                        verbose_name="Здание",
                    ),
                ),
            ],
            options={
                "verbose_name": "Реквизиты в сомах",
                "verbose_name_plural": "Реквизиты в сомах",
            },
        ),
        migrations.CreateModel(
            name="SalesOfficeBuilding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                ("description", models.TextField(verbose_name="Описание")),
                (
                    "building",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sales_offices",
                        to="objects.requisites",
                        verbose_name="Здание",
                    ),
                ),
            ],
            options={
                "verbose_name": "Офис продаж",
                "verbose_name_plural": "Офисы продаж",
            },
        ),
        migrations.CreateModel(
            name="SocialBuilding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=123, verbose_name="Название соц сети"),
                ),
                (
                    "svg",
                    models.FileField(
                        upload_to="socials/", verbose_name="Изображение SVG"
                    ),
                ),
                ("link", models.URLField(verbose_name="Ссылка")),
                (
                    "building",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="socials",
                        to="objects.requisites",
                        verbose_name="Здание",
                    ),
                ),
            ],
            options={
                "verbose_name": "Социальня сеть",
                "verbose_name_plural": "Социальные сети",
            },
        ),
    ]
