# Generated by Django 5.1.3 on 2025-01-14 18:31

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("objects", "0012_building_is_new"),
    ]

    operations = [
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("theme", models.CharField(blank=True, max_length=123, null=True)),
                ("name", models.CharField(max_length=123)),
                ("phone", models.CharField(max_length=123)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Заявка",
                "verbose_name_plural": "Заявки",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AboutUs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
                ("youtube_url_1", models.URLField()),
                ("youtube_url_2", models.URLField()),
                ("advantages", models.ManyToManyField(to="objects.advantage")),
            ],
            options={
                "verbose_name": "О нас",
                "verbose_name_plural": "О нас",
            },
        ),
        migrations.CreateModel(
            name="Section1",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", ckeditor.fields.RichTextField(verbose_name="Описание")),
                (
                    "about_us",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="section_1",
                        to="about.aboutus",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Section2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", ckeditor.fields.RichTextField(verbose_name="Описание")),
                (
                    "about_us",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="section_2",
                        to="about.aboutus",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Materials",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=244)),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="about.section2"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Section3",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", ckeditor.fields.RichTextField(verbose_name="Описание")),
                (
                    "about_us",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="section_3",
                        to="about.aboutus",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Section4",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", ckeditor.fields.RichTextField(verbose_name="Описание")),
                (
                    "about_us",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="section_4",
                        to="about.aboutus",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Gramota",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=123)),
                ("image", models.FileField(upload_to="images/gramotas/")),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="about.section4"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Section5",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=123)),
                ("description", ckeditor.fields.RichTextField()),
                (
                    "about_us",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="section_5",
                        to="about.aboutus",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Licence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=123)),
                ("image", models.FileField(upload_to="images/licence/")),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="about.section5"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Section6",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=123)),
                ("description", ckeditor.fields.RichTextField()),
                (
                    "about_us",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="section_6",
                        to="about.aboutus",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Sertificat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=123)),
                ("image", models.FileField(upload_to="images/licence/")),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="about.section6"
                    ),
                ),
            ],
        ),
    ]
