# Generated by Django 5.1.3 on 2024-12-13 19:32

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("info", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TechnicalBase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Заголовок")),
                ("description", ckeditor.fields.RichTextField(verbose_name="Описание")),
                (
                    "youtube_url",
                    models.URLField(
                        blank=True, null=True, verbose_name="Ссылка на YouTube"
                    ),
                ),
            ],
            options={
                "verbose_name": "Техническая база",
                "verbose_name_plural": "Техническая база",
            },
        ),
        migrations.CreateModel(
            name="TechnicalBaseImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="images/technical_base/", verbose_name="Изображение"
                    ),
                ),
                (
                    "technical_base",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="info.technicalbase",
                        verbose_name="Техническая база",
                    ),
                ),
            ],
            options={
                "verbose_name": "Изображение технической базы",
                "verbose_name_plural": "Изображения технической базы",
            },
        ),
    ]
