# Generated by Django 5.1.3 on 2025-01-22 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_technicalbase_technicalbaseimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacts',
            name='addresses',
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='requisites',
        ),
        migrations.AddField(
            model_name='contacts',
            name='inn',
            field=models.CharField(default='00412199810063 999 УГКНС ККН', max_length=123, verbose_name='ИНН'),
        ),
        migrations.AddField(
            model_name='contacts',
            name='okpo',
            field=models.CharField(default='22116708', max_length=123, verbose_name='ОКПО'),
        ),
        migrations.AddField(
            model_name='contacts',
            name='title',
            field=models.CharField(blank=True, default='ОсОО «Строительная компания «Авангард стиль»', max_length=255, verbose_name='Название компании'),
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=233, verbose_name='Название')),
                ('value', models.CharField(max_length=233, verbose_name='Адрес')),
                ('link', models.URLField(verbose_name='Ссылка на адрес')),
                ('contacts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='info.contacts', verbose_name='Контакты')),
            ],
            options={
                'verbose_name': 'Адрес',
                'verbose_name_plural': 'Адреса',
            },
        ),
        migrations.CreateModel(
            name='Socials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=123, verbose_name='Название соц сети')),
                ('svg', models.FileField(upload_to='socials/', verbose_name='Изображение SVG')),
                ('link', models.URLField(verbose_name='Ссылка')),
                ('contacts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='socials_ay', to='info.contacts', verbose_name='Контакты')),
            ],
            options={
                'verbose_name': 'Социальня сеть',
                'verbose_name_plural': 'Социальные сети',
            },
        ),
    ]
